### PR TITLE
Fix typos in qwtplot3d submodule

### PR DESCRIPTION
**Pull request by alxpl**

### CODE REVIEW

**Comment by alxpl** [comment]
I don't understand why the checks fail and I don't see how the CI system is set up.

I did look at what's being used in another qwtplot3d fork, Ubuntu Focal & Hirsute and Fedora::

```
$ grep -r -i grabframebuffer ./ | sort
./fedora/qwtplot3d-0.2.7/qwtplot3d/src/qwt3d_io.cpp:  QImage im = plot->grabFrameBuffer(true);
./original/qwtplot3d-0.2.7/qwtplot3d/src/qwt3d_io.cpp:  QImage im = plot->grabFrameBuffer(true);
./scidavis_fork/qwtplot3d-master/src/qwt3d_io.cpp:    QImage im = plot->grabFramebuffer();
./scidavis_fork/qwtplot3d-master/src/qwt3d_io_gl2ps.cpp:        plot->grabFramebuffer();
./sintegrial_fork/qwtplot3d-master/src/qwt3d_io.cpp://  QImage im = plot->grabFrameBuffer(true);
./sintegrial_fork/qwtplot3d-master/src/qwt3d_plot3d.cpp:    QImage img(grabFramebuffer());
./ubuntu_focal/qwtplot3d-0.2.7+svn191+gcc7.orig/src/qwt3d_io.cpp:  QImage im = plot->grabFrameBuffer(true);
./ubuntu_hirsute/qwtplot3d-0.2.7+svn191+gcc7.orig/src/qwt3d_io.cpp:  QImage im = plot->grabFrameBuffer(true);
```
The other fork is inconsistent, while everyone else is using the "grabFrameBuffer" spelling.

If anyone can figure out why the checks fail, please chime in.

**Comment by alxpl** [comment]
Can anyone offer any insight into this?

**Comment by gbm19** [comment]
Sorry for the delay.

grabFrameBuffer(bool) is a function of QGLWidget Class, an obsolete class in Qt5, deprecated and removed in Qt6. (https://doc.qt.io/archives/qt-5.5/qglwidget.html)

grabFramebuffer() is a function of QOpenGLWidget Class (https://doc.qt.io/qt-5/qopenglwidget.html), (https://doc.qt.io/qt-6/qopenglwidget.html)

Thus, grabFrameBuffer should not be used anymore.

**Comment by alxpl** [comment]
Hello Miquel,

My turn to apologize for the delay.
So, this PR should be scrapped, as the code is correct as it stands.
On the other hand, [PR#219](https://github.com/highperformancecoder/scidavis-old/pull/219) should be merged, as long as we are building SciDAVis with Qt5?

**Comment by gbm19** [comment]
No. Merging  [PR#219 ](https://github.com/highperformancecoder/scidavis-old/pull/219) would bring back the obsolete, no longer available "grabFrameBuffer" function of the obsolete QGLWidget class.

**Comment by alxpl** [comment]
> No. Merging [PR#219 ](https://github.com/highperformancecoder/scidavis-old/pull/219) would bring back the obsolete, no longer available "grabFrameBuffer" function of the obsolete QGLWidget class.

Then could you please check why the build fails on Fedora without that patch (when you have the time to spare)? I had absolutely no idea about either function until g++ said that grabFramebuffer() does not exist in whatever was imported.

**Comment by gbm19** [comment]
In Fedora 32,34  I can build and run all tests successfully with:

**Comment by gbm19** [comment]
In Fedora 32,34  I can build and run all tests successfully with:
`    cd /path/that/has/the/cloned/scidavis/repo`
`    mkdir build`
`    cd build`
`    cmake ..  -DORIGIN_IMPORT=ON -DSCRIPTING_PYTHON=ON -DBUILD_TESTS=ON -DBUILD_QWTPLOT3D=ON`
`    make`
`    make test`

In Fedora you cannot use the system library for qwtplot3d (qwtplot3d-qt5-0.3.1a-8.20170803git34d8141 in fc32,
qwtplot3d-qt5-0.3.1a-13.20200509git45df8fb in fc34)  because it is still using the obsolete class QGLWidget.

**Comment by alxpl** [comment]
> In Fedora you cannot use the system library for qwtplot3d (qwtplot3d-qt5-0.3.1a-8.20170803git34d8141 in fc32,
> qwtplot3d-qt5-0.3.1a-13.20200509git45df8fb in fc34) because it is still using the obsolete class QGLWidget.

I was afraid it was going to be something like this…
Essentially that means I can't build it on Fedora without the patch.
I'll ask Antonio who maintains qwtplot3d to see if anything can be done about this.

**Pull request closed without merging**
